# Generated by Django 5.2.11 on 2026-02-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
