# Generated by Django 5.2.11 on 2026-02-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitjob', '0003_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='user',
        ),
    ]
