# Generated by Django 5.2.11 on 2026-02-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitjob', '0004_rename_user_id_answer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
