# Generated by Django 5.2.11 on 2026-02-26 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitjob', '0005_rename_question_id_answer_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기 중'), ('RESOLVED', '처리 완료'), ('REJECTED', '반려')], default='PENDING', max_length=10)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitjob.answer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitjob.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('answer__isnull', True), ('question__isnull', False)), models.Q(('answer__isnull', False), ('question__isnull', True)), _connector='OR'), name='report_target_xor'), models.UniqueConstraint(fields=('user', 'question'), name='uniq_user_question_report'), models.UniqueConstraint(fields=('user', 'answer'), name='uniq_user_answer_report')],
            },
        ),
    ]
