# Generated by Django 5.2.11 on 2026-02-13 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='닉네임은 2~10자(한글/영문/숫자/_)만 가능합니다.', regex='^[가-힣a-zA-Z0-9_]{2,10}$'), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='아이디는 5~20자 영문/숫자만 가능합니다.', regex='^[a-zA-Z0-9]{5,20}$')]),
        ),
    ]
