# Generated by Django 5.2.11 on 2026-03-02 15:51

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_nickname_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to=user.models.user_profile_upload_path),
        ),
    ]
